# Um ein gültiges App-Passwort für john zu generieren:
# 1. Melden Sie sich als Administrator unter localhost:9000 (a@b.com / secret)
# 2. Auf der Kachel employee_api -> more Details --> edit
# 3. Links auf Directory --> Token and App Passwords
# 4. Klicken Sie auf "Create", wählen Sie einen Namen, wählen Sie john aus, wählen Sie App Password, deaktiviere expire klicken Sie auf "Create"
# 5. Kopieren Sie das generierte App-Passwort und verwenden Sie es im folgenden Befehl, um ein Bearer-Token zu erhalten.
@app_password=wscE0twURD7IVUx5s91Q6NdiFhSoGIZdhChR72SzQmGsF5hqZICYzz5hJCJ5
###
POST http://localhost:9000/application/o/token/
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=john&password={{app_password}}&client_id=employee_api_client

###